version: '4'

services:
  fin_api:
    image: postgres
    container_name: database_fin_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=fin_api
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin_api
    ports:
      - 3333:3333
    volumes:
    - .:/usr/app
    depends_on:
      - fin_api
    links:
      - fin_api
volumes:
  pgdata:
    driver: local
